# Auto-labeling configuration for pull requests
# https://github.com/actions/labeler#match-object

# Documentation changes
documentation:
- changed-files:
  - any-glob-to-any-file: ['**/*.md', 'docs/**']

# Device and hardware changes
device:
- changed-files:
  - any-glob-to-any-file: 'devices/**'

# Frontend/UI changes
frontend:
- changed-files:
  - any-glob-to-any-file: ['public/**', 'src/views/**']

# Backend/API changes
backend:
- changed-files:
  - any-glob-to-any-file: ['src/**', '!public/**']

# Testing changes
testing:
- changed-files:
  - any-glob-to-any-file: ['tests/**', '**/*.test.js', '**/*.spec.js', 'jest.config.js']

# CI/CD changes
ci-cd:
- changed-files:
  - any-glob-to-any-file: ['.github/**', 'Dockerfile', '.dockerignore']

# Configuration changes
config:
- changed-files:
  - any-glob-to-any-file: ['package*.json', '.env*', '*.config.js', '.husky/**']

# Script changes
scripts:
- changed-files:
  - any-glob-to-any-file: 'scripts/**'

# Security-related changes
security:
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/security.yml', 'package-lock.json']

# Branch-based labels
feature:
- head-branch: ['^feature', 'feat']

bugfix:
- head-branch: ['^fix', '^bug', 'bugfix']

hotfix:
- head-branch: ['^hotfix']

# Release-related
release:
- head-branch: ['^release', '^rel']
