version: '3.8'

services:
  dmx-controller:
    build: .
    container_name: dmx-controller
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DMX_DEVICE=${DMX_DEVICE:-/dev/ttyUSB0}
    devices:
      # USB DMX Interface - adjust path as needed
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      # Persist logs
      - ./logs:/app/logs
      # Optional: Custom configuration
      - ./.env:/app/.env:ro
    networks:
      - dmx-network

networks:
  dmx-network:
    driver: bridge
